name: Generate new Release
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Test action
            uses: kimdre/cloud-init-linter@main
