name: Test Action
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Test action
            uses: kimdre/cloud-init-linter@83e50b85d1c6b8288694d70128d3af773bf69dcc
